### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by jokeyrhyme** [mgcrea/generator-angular-component#2]
Getting this error with version 0.2.1:

```
$ yo angular-component

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-component/node_modules/yeoman-generator/lib/util/common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-component/node_modules/yeoman-generator/lib/base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Here's the output from my `npm -g ls` if that helps:
https://gist.github.com/jokeyrhyme/6422170

The problem seems to be in the version of yeoman-generator that is required (0.12.2). I've noticed that there's a newer version of yeoman-generator available now.

**Comment by ryannorris** [comment]
I'm seeing the same chaos show up in other community generators as well: https://github.com/yeoman/generator-mobile/issues/10

**Comment by pablojim** [comment]
+1

**Comment by findzen** [comment]
I've completely removed yeoman, including the CLI and generators, cleaned npm cache and reinstalled. Still seeing the same thing.

**Comment by pablojim** [comment]
I think the fix hasn't been pushed to npm yet.  Install it from the github url and it will work.

**Comment by rogerz** [comment]
+1. Install from git is OK for now.

```
npm install -g git+https://github.com/mgcrea/generator-angular-component.git
```

**Comment by mgcrea** [comment]
Just pushed a new release, this should be good now. Thanks.

**Comment by therealklanni** [comment]
The version on [npmjs.org](https://npmjs.org/package/generator-angular-component) is still **0.2.1**.

**Comment by edmondop** [comment]
Still not working for me
